apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-lab19
  labels:
    app: frontend-lab19
spec:
  selector:
    matchLabels:
      app: frontend-lab19
  replicas: 1
  template:
    metadata:
      labels:
        app: frontend-lab19
    spec:
      containers:
        - name: frontend-lab19
          image: thhel123/front-service
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
